spring:
  application:
    name: aweather-mobile-web

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 20000
        read-timeout: 20000